<a href="https://colab.research.google.com/github/nitindavegit/Deep-Learning/blob/main/pytorch02_autograd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
def dx_dy(x):
  return 2*x

In [2]:
print(dx_dy(3))

6


In [3]:
import math
def dz_dx(x):
  return 2 * x * math.cos(x ** 2)

In [4]:
dz_dx(5)

9.912028118634735

In [5]:
import torch

In [6]:
torch.tensor([1,2,3])

tensor([1, 2, 3])

In [7]:
torch.tensor(1)

tensor(1)

In [8]:
torch.tensor([1])

tensor([1])

In [9]:
x = torch.tensor(3.00, requires_grad=True)

In [10]:
y = x ** 2

In [11]:
x

tensor(3., requires_grad=True)

In [12]:
y

tensor(9., grad_fn=<PowBackward0>)

In [13]:
y.backward()

In [14]:
x.grad

tensor(6.)

In [15]:
x = torch.tensor(3.0, requires_grad=True)

In [16]:
y = x ** 2

In [17]:
z = torch.sin(y)

In [18]:
x

tensor(3., requires_grad=True)

In [19]:
y

tensor(9., grad_fn=<PowBackward0>)

In [20]:
z

tensor(0.4121, grad_fn=<SinBackward0>)

In [21]:
z.backward()

In [22]:
x.grad

tensor(-5.4668)

# ***Example***

In [23]:
import torch
x = torch.tensor(6.7)  # input
y = torch.tensor(0.0)  # real answer

w = torch.tensor(1.0) # weight
b = torch.tensor(0.0) # bias


In [24]:
# Binary cross entropy loss for scalar
def binary_cross_entropy_loss(prediction, target):
  epsilon = 1e-8
  prediction = torch.clamp(prediction, epsilon,1 - epsilon )
  return - (target * torch.log(prediction) + (1 - target) * torch.log(1 - prediction))

In [25]:
# Forward pass
z = w * x + b
y_pred = torch.sigmoid(z)

# compute loss
loss = binary_cross_entropy_loss(y_pred,y)

In [26]:
# all derivatives
dloss_dy_pred = (y_pred - y) / (y_pred * (1 - y_pred))
dy_pred_dz = y_pred * (1 - y_pred)
dz_dw = x
dz_db = 1
dL_dw = dloss_dy_pred * dy_pred_dz * dz_dw
dL_db = dloss_dy_pred * dy_pred_dz * dz_db

In [27]:
print(f"Manual gradient of loss w.r.t. weight : {dL_dw}")
print(f"Manual gradient of loss w.r.t. bias : {dL_db}")

Manual gradient of loss w.r.t. weight : 6.691762447357178
Manual gradient of loss w.r.t. bias : 0.998770534992218


## **`*Mentos zindagi*`**

In [28]:
x = torch.tensor(6.7)
y = torch.tensor(0.0)

In [29]:
w = torch.tensor(1.0,requires_grad=True)
b = torch.tensor(0.0, requires_grad=True)

In [30]:
z = w*x + b
z

tensor(6.7000, grad_fn=<AddBackward0>)

In [31]:
y_pred = torch.sigmoid(z)
y_pred

tensor(0.9988, grad_fn=<SigmoidBackward0>)

In [32]:
loss = binary_cross_entropy_loss(y_pred, y)
loss

tensor(6.7012, grad_fn=<NegBackward0>)

In [33]:
loss.backward()

In [34]:
print(w.grad)
print(b.grad)

tensor(6.6918)
tensor(0.9988)


## ***Using Vector inputs***

In [35]:
x = torch.tensor([1.0,2.0,3.0], requires_grad=True)
x

tensor([1., 2., 3.], requires_grad=True)

In [36]:
y = (x ** 3).median()
y

tensor(8., grad_fn=<MedianBackward0>)

In [37]:
y.backward()

In [38]:
x.grad

tensor([ 0., 12.,  0.])

# Clearing Grad

In [39]:
x.grad.zero_()

tensor([0., 0., 0.])

*How to disable gradient tracking*

In [40]:
# option 1
x.requires_grad_(False)

tensor([1., 2., 3.])

In [41]:
# option 2
z = x.detach()

In [42]:
# option 3
with torch.no_grad():
  y = x ** 2