<a href="https://colab.research.google.com/github/nitindavegit/Deep-Learning/blob/main/pytorch06_Dataset_and_DataLoader_class.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

We were using batch gradient descent. i.e. entire dataset is going to forward pass, then loss calculation and then backward pass etc.
which has 2 major flaws:
1. **Memory ineffecient**
2. **Better Convergence**

**Solution** : *Rather than loading the entire dataset , load the batches of dataset*

In [27]:
from sklearn.datasets import make_classification
import torch

# Create a Synthetic classification dataset using sklearn

In [28]:
X, y = make_classification(
    n_samples=10,         # Number of samples
    n_features=2,         # Number of features
    n_informative=2,      # Number of informative features
    n_redundant=0,        # Number of redundant features
    n_classes=2,          # Number of classes
    random_state=42       # for reproducibility
)

In [29]:
X

array([[ 1.06833894, -0.97007347],
       [-1.14021544, -0.83879234],
       [-2.8953973 ,  1.97686236],
       [-0.72063436, -0.96059253],
       [-1.96287438, -0.99225135],
       [-0.9382051 , -0.54304815],
       [ 1.72725924, -1.18582677],
       [ 1.77736657,  1.51157598],
       [ 1.89969252,  0.83444483],
       [-0.58723065, -1.97171753]])

In [30]:
y

array([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

In [31]:
print(X.shape)
print(y.shape)

(10, 2)
(10,)


# Convert data to pytorch tensors

In [32]:
X = torch.tensor(X, dtype=torch.float32)
y = torch.tensor(y, dtype=torch.long)   # long = int64

# Import Dataset and DataLoader

In [33]:
from torch.utils.data import Dataset, DataLoader

# Create a custom class

In [34]:
class CustomDataSet(Dataset):
  def __init__(self, features, labels):
    self.features = features         # features is X
    self.labels = labels             # labels is y

  def __len__(self):
    return self.features.shape[0]       # or len(self.features)

  def __getitem__(self,index):
    return self.features[index], self.labels[index]

# Create an instance of CustomDataSet

In [35]:
dataset = CustomDataSet(X,y)

In [36]:
len(dataset)

10

In [37]:
dataset[8]

(tensor([1.8997, 0.8344]), tensor(1))

# Create an instance of DataLoader

In [38]:
# mention batch_size and shuffle parameter
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

In [39]:
# batches will form of 2 and it would be randomly arranged

for batch_features, batch_labels in dataloader:
  print(batch_features)
  print(batch_labels)
  print("-"*50)

tensor([[-0.7206, -0.9606],
        [ 1.7273, -1.1858]])
tensor([0, 1])
--------------------------------------------------
tensor([[-2.8954,  1.9769],
        [ 1.8997,  0.8344]])
tensor([0, 1])
--------------------------------------------------
tensor([[ 1.0683, -0.9701],
        [-0.5872, -1.9717]])
tensor([1, 0])
--------------------------------------------------
tensor([[-1.9629, -0.9923],
        [-1.1402, -0.8388]])
tensor([0, 0])
--------------------------------------------------
tensor([[ 1.7774,  1.5116],
        [-0.9382, -0.5430]])
tensor([1, 1])
--------------------------------------------------
