<a href="https://colab.research.google.com/github/nitindavegit/Deep-Learning/blob/main/pytorch01_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
print(torch.__version__)

2.8.0+cu126


In [ ]:
if torch.cuda.is_available():
  print("GPU is available")
  print(torch.cuda.get_device_name(0))
else:
  print("GPU not available")

GPU is available
Tesla T4


### Creating a **tensor**

In [ ]:
# using empty
t = torch.empty(3,3)  # as it is assign address and  give its previous  value

In [ ]:
# check type
type(t)

torch.Tensor

In [ ]:
# using zeros
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [ ]:
torch.zeros(4)

tensor([0., 0., 0., 0.])

In [ ]:
# using ones
torch.ones(1,5)

tensor([[1., 1., 1., 1., 1.]])

In [ ]:
# using rand
torch.rand(2,4)

tensor([[0.8105, 0.5983, 0.5705, 0.4717],
        [0.2329, 0.0121, 0.6449, 0.9818]])

In [ ]:
torch.rand(5)

tensor([0.5005, 0.7480, 0.9552, 0.5466, 0.1976])

In [ ]:
# using seed
torch.manual_seed(5)
a = torch.rand(1,2)
b = torch.rand(1,2)
e = torch.rand(1,1)
print(a)
print(b)
print(e)

tensor([[0.8303, 0.1261]])
tensor([[0.9075, 0.8199]])
tensor([[0.9201]])


In [ ]:
torch.manual_seed(5)
c = torch.rand(1,2)
d = torch.rand(1,2)
f = torch.rand(1,1)
print(c)
print(d)
print(f)

tensor([[0.8303, 0.1261]])
tensor([[0.9075, 0.8199]])
tensor([[0.9201]])


In [ ]:
# Using tensor
z = torch.tensor([[1,2,3],[7,8,9]])
z

tensor([[1, 2, 3],
        [7, 8, 9]])

In [ ]:
# Other ways

# arange
print(torch.arange(1,10,3))
print(torch.arange(0,15,1).reshape(3,5)) # perfectly sync rows and columns

# using linspace
print(torch.linspace(1,5,10))

# using eye
print(torch.eye(6))

# using full
print(torch.full((2,3),3))

tensor([1, 4, 7])
tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])
tensor([1.0000, 1.4444, 1.8889, 2.3333, 2.7778, 3.2222, 3.6667, 4.1111, 4.5556,
        5.0000])
tensor([[1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 1.]])
tensor([[3, 3, 3],
        [3, 3, 3]])


## **Tensor SHapes**

In [ ]:
x = torch.tensor([[1,2],[3,4],[5,6]])
x

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [ ]:
x.shape

torch.Size([3, 2])

In [ ]:
torch.empty_like(x)

tensor([[3180222411935070754, 8391722768137527840],
        [7959390389040738153, 2318286393299313268],
        [8675445202132104482, 7957695011165139568]])

In [ ]:
torch.zeros_like(x)

tensor([[0, 0],
        [0, 0],
        [0, 0]])

In [ ]:
torch.ones_like(x)

tensor([[1, 1],
        [1, 1],
        [1, 1]])

In [ ]:
torch.rand_like(x,dtype=torch.float32)

tensor([[0.1166, 0.1644],
        [0.7379, 0.0333],
        [0.9942, 0.6064]])

## ***Tensor Data Types***

In [ ]:
# find data type
x.dtype

torch.int64

In [ ]:
# assign a datatype
torch.tensor([[1,2,3],[11,12,13]],dtype=torch.int64)

tensor([[ 1,  2,  3],
        [11, 12, 13]])

In [ ]:
# using to()
x.to(torch.float32)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

# **Mathematical Operations**

---



## ***1. Scalar Operation***

In [ ]:
y = torch.rand((3,3))
y

tensor([[0.5646, 0.0724, 0.6593],
        [0.7150, 0.5793, 0.9809],
        [0.6502, 0.0566, 0.9201]])

In [ ]:
# addition
print(y + 3)

# subtraction
print(y-3)

# multiplication
print(y*2)

# division
print(y/2)

# int division
print(y*100 // 2)

# power
print(y ** 3)

# mod
y.to(torch.int32)
print(y % 4)

tensor([[3.5646, 3.0724, 3.6593],
        [3.7150, 3.5793, 3.9809],
        [3.6502, 3.0566, 3.9201]])
tensor([[-2.4354, -2.9276, -2.3407],
        [-2.2850, -2.4207, -2.0191],
        [-2.3498, -2.9434, -2.0799]])
tensor([[1.1291, 0.1448, 1.3187],
        [1.4300, 1.1587, 1.9619],
        [1.3003, 0.1133, 1.8402]])
tensor([[0.2823, 0.0362, 0.3297],
        [0.3575, 0.2897, 0.4905],
        [0.3251, 0.0283, 0.4601]])
tensor([[28.,  3., 32.],
        [35., 28., 49.],
        [32.,  2., 46.]])
tensor([[1.7995e-01, 3.7970e-04, 2.8663e-01],
        [3.6553e-01, 1.9443e-01, 9.4387e-01],
        [2.7483e-01, 1.8165e-04, 7.7897e-01]])
tensor([[0.5646, 0.0724, 0.6593],
        [0.7150, 0.5793, 0.9809],
        [0.6502, 0.0566, 0.9201]])


## 2. ***Element Wise Operation***

In [ ]:
a = torch.rand(2,2)
b = torch.rand(2,2)
print(a)
print(b)

tensor([[0.6698, 0.2615],
        [0.0407, 0.7850]])
tensor([[0.9752, 0.0903],
        [0.5273, 0.6794]])


In [ ]:
# add
a + b

# sub
a-b

# mul
a * b

# div
a / b

# power
a ** b

# mod
a % b

tensor([[0.6698, 0.0808],
        [0.0407, 0.1056]])

In [ ]:
c = torch.tensor([1,2,-4,-9])

In [ ]:
torch.abs(c)

tensor([1, 2, 4, 9])

In [ ]:
# negative
torch.neg(c)

tensor([-1, -2,  4,  9])

In [ ]:
d = torch.tensor([1.9,2.3,3.7,4.4])

In [ ]:
torch.round(d)

tensor([2., 2., 4., 4.])

In [ ]:
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [ ]:
torch.floor(d)

tensor([1., 2., 3., 4.])

In [ ]:
torch.clamp(d,min=2,max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

## 3. ***Reduction Operation***

In [ ]:
e = torch.randint(size=(2,3),low=0, high=10, dtype=torch.float32)
e

tensor([[9., 2., 6.],
        [0., 2., 2.]])

In [ ]:
# sum
torch.sum(e)

# sum along columns
torch.sum(e, dim=0)

# sum along rows
torch.sum(e,dim=1)

tensor([17.,  4.])

In [ ]:
# mean
torch.mean(e)

torch.mean(e, dim=0)

torch.mean(e, dim=1)

tensor([5.6667, 1.3333])

In [ ]:
# median
torch.median(e)

tensor(2.)

In [ ]:
# max and min
torch.max(e)
torch.min(e)

tensor(0.)

In [ ]:
# product
torch.prod(e)

tensor(0.)

In [ ]:
# std
torch.std(e)

# var
torch.var(e)

tensor(11.1000)

In [ ]:
# argmax
torch.argmax(e)
# argmin
torch.argmin(e)

tensor(3)

## **4. Matrix Operation**

In [ ]:
f = torch.randint(size=(2,3),low=0,high=10)
g = torch.randint(size=(3,2),low=0,high=10)

In [ ]:
print(f)
print()
print(g)

tensor([[6, 9, 9],
        [1, 7, 2]])

tensor([[6, 4],
        [1, 7],
        [9, 0]])


In [ ]:
# matrix multiplication
print(torch.matmul(f,g))
print()
print(torch.matmul(g,f))

tensor([[126,  87],
        [ 31,  53]])

tensor([[40, 82, 62],
        [13, 58, 23],
        [54, 81, 81]])


In [ ]:
v1 = torch.tensor([1,2])
v2 = torch.tensor([3,4])
# dot product
print(torch.dot(v1,v2))
print(torch.dot(v2,v1))

tensor(11)
tensor(11)


In [ ]:
# transpose
torch.transpose(f,0,1)

tensor([[6, 1],
        [9, 7],
        [9, 2]])

In [ ]:
h = torch.randint(size=(3,3),low=0,high=15, dtype=torch.float32)
h

tensor([[ 1., 12.,  5.],
        [ 9., 13., 14.],
        [ 9., 14.,  8.]])

In [ ]:
# determinant
torch.det(h)

tensor(601.0001)

In [ ]:
# inverse
torch.inverse(h)

tensor([[-0.1531, -0.0433,  0.1714],
        [ 0.0899, -0.0616,  0.0516],
        [ 0.0150,  0.1564, -0.1581]])

## **5. Comparison Operations**

In [ ]:
i = torch.randint(size=(2,3),low=0,high=15)
j = torch.randint(size=(2,3),low=0,high=15)
print(i)
print(j)

tensor([[ 5,  0,  3],
        [ 5, 11, 11]])
tensor([[12,  6,  1],
        [ 4,  2,  6]])


In [ ]:
# greater than
i > j
# less than
i < j
# equal to
i == j
# not equal to
i != j
# greater than or equal
i >= j
# less or equal
i <= j


tensor([[ True,  True, False],
        [False, False, False]])

## **6. Special functions**

In [ ]:
k = torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
k

tensor([[6., 4., 8.],
        [1., 9., 6.]])

In [ ]:
# log
torch.log(k)

tensor([[1.7918, 1.3863, 2.0794],
        [0.0000, 2.1972, 1.7918]])

In [ ]:
# exp
torch.exp(k)

tensor([[4.0343e+02, 5.4598e+01, 2.9810e+03],
        [2.7183e+00, 8.1031e+03, 4.0343e+02]])

In [ ]:
# sqrt
torch.sqrt(k)

tensor([[2.4495, 2.0000, 2.8284],
        [1.0000, 3.0000, 2.4495]])

In [ ]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9975, 0.9820, 0.9997],
        [0.7311, 0.9999, 0.9975]])

In [ ]:
# softmax
torch.softmax(k, dim=0)

tensor([[0.9933, 0.0067, 0.8808],
        [0.0067, 0.9933, 0.1192]])

In [ ]:
# relu
torch.relu(k)

tensor([[6., 4., 8.],
        [1., 9., 6.]])

# ***Inplace Operations***

In [ ]:
m = torch.rand(2,3)
n = torch.rand(2,3)
print(m)
print(n)

tensor([[0.9170, 0.5823, 0.6512],
        [0.2791, 0.8470, 0.3125]])
tensor([[0.2308, 0.9535, 0.6325],
        [0.4965, 0.1515, 0.3893]])


In [ ]:
m.add_(n)

tensor([[1.1477, 1.5358, 1.2836],
        [0.7756, 0.9986, 0.7018]])

# ***Copying a Tensor***

In [ ]:
a = torch.rand(2,2)
a

tensor([[0.1159, 0.1636],
        [0.4284, 0.5967]])

In [ ]:
b = a.clone()
b

tensor([[0.1159, 0.1636],
        [0.4284, 0.5967]])

# ***Tensor operations on GPU***

In [ ]:
torch.cuda.is_available()

True

In [ ]:
device = torch.device('cuda')

In [ ]:
# create new tensors on GPU
torch.rand((3,3),device=device)

tensor([[0.7660, 0.3875, 0.7305],
        [0.1861, 0.9196, 0.4495],
        [0.0151, 0.6044, 0.3293]], device='cuda:0')

In [ ]:
# Moving old tensor into GPU
a = torch.rand(2,3)
a

tensor([[0.0903, 0.9860, 0.8677],
        [0.0347, 0.8125, 0.2000]])

In [ ]:
b = a.to(device)

In [ ]:
# Testing
import torch
import time
# size of matrices
size = 10000

# random tensors on CPU
matrix_cpu1 = torch.randn(size,size)
matrix_cpu2 = torch.randn(size,size)
# Measure time on CPU
start_time = time.time()
result_cpu = torch.matmul(matrix_cpu1, matrix_cpu2)
cpu_time = time.time() - start_time

print(f"Time on CPU: {cpu_time: .4f} seconds")

# Move matrices to GPU
matrix_gpu1 = matrix_cpu1.to(device)
matrix_gpu2 = matrix_cpu2.to(device)

# Measure time
start_time = time.time()
result_gpu = torch.matmul(matrix_gpu1, matrix_gpu2)
gpu_time = time.time() - start_time

print(f"Time on GPU: {gpu_time: .4f} seconds")

Time on CPU:  15.7567 seconds
Time on GPU:  0.1295 seconds


# ***Reshaping Tensors***

In [ ]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
# reshape
a.reshape(2,8)

tensor([[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
# flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
b = torch.randint(size=(2,3,4), low=0, high=12)

b

tensor([[[ 5,  0,  9,  1],
         [ 5,  8,  1, 10],
         [11,  9,  4,  9]],

        [[ 9,  7,  7,  0],
         [ 9,  8, 10, 10],
         [10, 11, 11,  6]]])

In [ ]:
# permute
b.permute(2,1,0).shape

torch.Size([4, 3, 2])

In [ ]:
# unsqueeze
c = torch.rand(226,226,3)  # image size
c.unsqueeze(2).shape

torch.Size([226, 226, 1, 3])

In [ ]:
# squeeze
d = torch.rand(1,20)
d.squeeze(0).shape

torch.Size([20])

# ***Numpy and Pytorch***

In [ ]:
import numpy as np
a= torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [ ]:
b =a.numpy()

In [ ]:
type(b)

numpy.ndarray

In [ ]:
c= np.array([3,4,5])
c

array([3, 4, 5])

In [ ]:
torch.from_numpy(c)

tensor([3, 4, 5])